language: node_js
node_js:
  - lts/*
install:
  - npm install # yarn install
script:
  - npm run docs:build # yarn docs:build
  - npm run cname
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面
  github_token: $GITHUB_TOKEN进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: master